name: html lint
  
on:
  push:
    branches:
      - master
    paths:
      - '*.html'
      - '.tidyrc'
      - '.github/workflows/tidy.yml'

  pull_request:
    branches:
      - master
    paths:
      - '*.html'
      - '.tidyrc'
      - '.github/workflows/tidy.yml'

jobs:
  lint:
    name: Run html linter 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt install tidy 

      - name: Run tidy
        run: |
          tidy -config .tidyrc *.html
